# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './bovo_client/package-lock.json'
    - name: Install dependencies
      working-directory: ./bovo_client # npm i 명령을 실행할 디렉토리 지정
      run: npm i

    - name: Build # 기존 Build 스텝을 수정
      working-directory: ./bovo_client # npm run build 명령을 실행할 디렉토리 지정
      run: npm run build --if-present
      env: # <<<--- 이 env 블록을 추가합니다!
        VITE_BACKEND_API_URL: ${{secrets.VITE_BACKEND_API_URL}}
        VITE_KAKAO_LOGIN_API_KEY: ${{ secrets.VITE_KAKAO_LOGIN_API_KEY }} # PR에서 에러가 계속된다면, 이 값을 dummy_key_for_pr_test 등으로 임시 변경 고려
        VITE_KAKAO_REDIRECT_URI: ${{ vars.VITE_KAKAO_REDIRECT_URI_PR }}
        VITE_WS_API_URL: ${{ vars.VITE_WS_API_URL_PR }}
        VITE_BACKEND_SEARCH_API_URL: ${{ vars.VITE_BACKEND_SEARCH_API_URL_PR }}

    # - name: Test
    #   working-directory: ./bovo_client # npm test 명령을 실행할 디렉토리 지정
    #   run: npm test

    - uses: awact/s3-action@master
      with:
        args: --delete
      env:
          SOURCE_DIR: './bovo_client/dist'
          AWS_REGION: 'ap-northeast-2'
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
